spring:
  datasource:
    url: jdbc:mysql://rm-2vc59woa16e3tm61qao.mysql.cn-chengdu.rds.aliyuncs.com:3306/free-fs?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: supercharge
    password: 2ObNP8pRulGvWvDMhzpGfIp
    driver-class-name: com.mysql.cj.jdbc.Driver
##### mybatis-plus打印完整sql(只适用于开发环境)
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

fs:
  isPreview: false
